/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NFTA (https://sketchfab.com/nfta)
license: COPYRIGHT TO NFTA
source: https://sketchfab.com/3d-models/msk-383e5ce596e84e6996afa560eb0ebf63
title: mısk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/scene-transformed.glb')
  return (
    //<group position={[-82, -167, -50]}>
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-82, -167, -50]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials['16___Default']} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['16___Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/scene-transformed.glb')
